### PR TITLE
Localize FluentHub

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
### ⏱️ Before you start

Relying on AZP to build the app.

### ↗️ Related/Fixed issues

- Related: #240 

### 📄 Description

Add all strings to resource files.

### CODE REVIEW

**Comment by DeveloperWOW64** [comment]
lool now i need to relocalise mainpage

**Comment by DeveloperWOW64** [comment]
@onein528 Localising settings pages that aren't Account/Appearance pages will be difficult as they don't work for me. Do they work for you? Or is that just a problem on my machine?

**Comment by onein528** [comment]
Shouldn't touch settings pages. It's under construction. Very unstable and undeveloped.

**Comment by onein528** [comment]
I will develop them. Sorry inconvenient

**Comment by DeveloperWOW64** [comment]
> I will develop them. Sorry inconvenient

No problem!

**Comment by onein528** [comment]
I hate ‘s’.....

**Comment by DeveloperWOW64** [comment]
> I hate ‘s’.....

I hate 'z'.....

**Comment by hunterlan** [comment]
> > I hate ‘s’.....
> 
> I hate 'z'.....

i18n? :D

**Review by onein528 — APPROVED** [review]
You're really nice! LGTM, so far.

**Comment by onein528** [comment]
Btw, can you fix automated Azure Pipeline builds errors?

**Comment by onein528** [comment]
Can I merge this? @DeveloperWOW64

**Review by onein528 — APPROVED** [review]
LGTM. Good work!

**Comment by DeveloperWOW64** [comment]
> Can I merge this? @DeveloperWOW64

Hmm. @onein528 Not really, as I haven't done everything I planned to, but I have school now so I if I continued it would be slow, eventual work. But it's still possible.
Here's my checklist:
- [x] AppSettings (sort of)
- [x] Home
- [ ] Organizations
- [ ] Repositories
- [x] SignIn (as completed by you ofc)
- [ ] Users
- [x] MainPage

**Comment by onein528** [comment]
I have breaking changes in ‘Improve error handling’. It's a really breaking change.  Conflicts....

**Comment by DeveloperWOW64** [comment]
> I have breaking changes in ‘Improve error handling’. It's a really breaking change. Conflicts....

Okay. Then you can merge. After you merge #251 I will move to WASDK and then we can finish localisation. What do you think @onein528.

**Comment by onein528** [comment]
Really nice.

**Pull request merged**
