### PR TITLE
Update grammar in activities page

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
### Before you start

- [x] Have you checked if a similar PR has already been requested?
- [x] PR is mergeable
- [ ] Have you built and ran the app?

###### <sup>Address related/fixed issues</sup>

None

###### <sup>Details of changes are listed here</sup>
As in the title

###### <sup>Items resolved/related issues by this PR.</sup>
As in the title

###### <sup>A list of assets (screenshots, mockups) relevant to this pull request.</sup>
None

### CODE REVIEW

**Comment by nathayoung** [comment]
You spelled successful wrong

**Review by nathayoung — CHANGES_REQUESTED** [review]
You spelled successful wrong.

**Comment by nathayoung** [comment]
I would have fixed it but I don't have permission and don't want to fork for an 's' lol

**Comment by onein528** [comment]
Can you tell me what's wrong or where's wrong?

**Review by ioapiset — APPROVED** [review]
Good enough.

**Pull request merged**
