### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by onein528**
### ⏱️ Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### ↗️ Related/Fixed issues

_None_

### 📄 Description

As  the title

### 💭 Motivation and Context

- [x] Improve exception handling
- [x] Aggregate all async tasks into one async task so that they can be caught wherever exceptions occur.
- [x] Add new exception display page
- [x] Add new exception details dialog

Applied on:

- [x] User pages
- [x] Repository pages
- [x] Home pages
- [x] Organization pages

Clean up:

- [x] Clean-up

### 📸 Assets (if appropriate):

image

image

### CODE REVIEW

**Review by DeveloperWOW64 — COMMENTED** [review]
@onein528 What on earth did you do b5066548c8299b1c0f659958acb68547687fb339 for?

**Comment by onein528** [comment]
Ahh, what is ‘this’?

**Comment by DeveloperWOW64** [comment]
> @onein528 What on earth did you do [b506654](https://github.com/FluentHub/FluentHub/commit/b5066548c8299b1c0f659958acb68547687fb339) for?

It breaks the search system.

**Comment by onein528** [comment]
WHAT? No I didn't break any feature. Look at it carefully. I created some duplicated attribution by main fetching. So I deleted them.

**Comment by onein528** [comment]
More information:

image

image

image

**Comment by DeveloperWOW64** [comment]
Ahh. Sorry.

**Comment by onein528** [comment]
You can see nicer error page! Just try it out.

**Comment by DeveloperWOW64** [comment]
I ABSOLUTELY LOVE THIS
image
I will fix the spelling. Good work, @onein528! 😄

**Comment by DeveloperWOW64** [comment]
BTW @onein528 Please use strings from now on.

**Comment by onein528** [comment]
OK! Thanks. I also will.

**Comment by DeveloperWOW64** [comment]
@onein528 I'd set a custom title bar element like in SignIn so the profile/home/explore/tabview etc. are hidden.

**Comment by onein528** [comment]
WDYM?

**Comment by DeveloperWOW64** [comment]
> WDYM?

@onein528 SignIn has a custom titlebar element (aka no titlebar) 
image
So, I think it should be the same for the Error page.

**Comment by onein528** [comment]
You mean to want to hide left side navigation view and replace the title bar with custom one?

**Comment by DeveloperWOW64** [comment]
> You mean to want to hide left side navigation view and replace the title bar with custom one?

Yep.

**Comment by onein528** [comment]
Why did you think that it should be hidden?

**Comment by DeveloperWOW64** [comment]
> Why did you think that it should be hidden?

Because it's unnecessary. If the user has an error that prevents them from going forth, they don't need to be able to use the rest of the app as it is likely to have a similar error. I think you misunderstand. I suggest this from a design perspective, not a functional one.

**Comment by onein528** [comment]
Almost of all exceptions are not recoverable. But network disconnectio exception titled 'An error occurred while sending the request' is reconverable and general exception error. I think the app should provide page as it is to restart immediately whenever network is back for user. Yes design issue I know but this could be functional issue.

**Comment by DeveloperWOW64** [comment]
> Almost of all exceptions are not recoverable. But network disconnectio exception titled 'An error occurred while sending the request' is reconverable and general exception error. I think the app should provide page as it is to restart immediately whenever network is back for user. Yes design issue I know but this could be functional issue.

But we still have a 'refresh' button. @onein528

**Comment by onein528** [comment]
Let it be clear. clicking 'Try Again', that left-side navigation view will be back?

**Comment by DeveloperWOW64** [comment]
> Let it be clear. clicking 'Try Again', that left-side navigation view will be back?

Yep. But only if the error is resolved after clicking 'Try Again' ofc. @onein528

**Comment by onein528** [comment]
Good. I'll try to do that.

**Comment by onein528** [comment]
Why did you reset label from high pri to medium pri?

**Comment by DeveloperWOW64** [comment]
> Why did you reset label from high pri to medium pri?

Why so high priority? @onein528

**Comment by onein528** [comment]
High: Must be
Med: Should be
Low: Could be

**Comment by onein528** [comment]
@DeveloperWOW64 can you see UserControls/Overview/RepositoryOverview.xaml and it's inside Stargizer count badge and it's converter? It is way better than previous converter as helper methods. What do you think?

**Comment by onein528** [comment]
New

image

**Review by ioapiset — APPROVED** [review]
LGTM.

**Pull request merged**
