### PR TITLE
Experimental PR for GraphQL.Client

### PR DESCRIPTION
**Pull request by onein528**
### Before you start

- [ ] Have you checked if a similar PR has already been requested? 
- [ ] Have you built and ran the app?

###### <sup>Address related/fixed issues</sup>

- Related: #
- Fixed: #

### CODE REVIEW

**Comment by onein528** [comment]
@DeveloperWOW64 Same issue he has. so not FluentHub only. try this PR continue?

image

**Comment by onein528** [comment]
But now abandon publishing to release pages. still use Octokit.GraphQL.NET sorry I have no time to update entire Octokit class.

**Comment by DeveloperWOW64** [comment]
@onein528 If you could update the Octokit class would this PR fix the Select() problem?

**Comment by onein528** [comment]
I'll take a look

**Comment by DeveloperWOW64** [comment]
Ah yes onein, definitely abandoned.. not
image
[`085f232`](https://github.com/octokit/octokit.graphql.net/commit/085f23228278a790c9711d6527d00a301082a3f2)

**Pull request closed without merging**
