### PR TITLE
Check events before accessing them (anti-nullreferenceexception)

### PR DESCRIPTION
**Pull request by GermanAizek**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### Related/Fixed issues
- Related: None
- Fixed: None

### Description
Checks for events before accessing them, prevents NullReferenceException

### CODE REVIEW

**Review by onein528 — APPROVED** [review]
LGTM. Thank you!

**Comment by onein528** [comment]
> > Checks for events before accessing them, prevents NullReferenceException
> 
> 
> 
> Welcome @GermanAizek!
> 
> I've requested the lead developer's review for this PR; looking good!
> 
> 

Also you can review. and then i will merge.

**Comment by onein528** [comment]
@GermanAizek You did not try to build before you open this PR?

**Comment by GermanAizek** [comment]
@onein528, I corrected it here https://github.com/FluentHub/FluentHub/pull/157

**Pull request merged**
