### PR TITLE
Update README screenshots

### PR DESCRIPTION
**Pull request by DeveloperWOW64**

### CODE REVIEW

**Comment by onein528** [comment]
Can I ask the pages?

**Comment by DeveloperWOW64** [comment]
@onein528 please review.

**Review by onein528 — CHANGES_REQUESTED** [review]
Sorry for being so detailed...

- Remove Home page
- Larger window
- Use light mode

**Comment by DeveloperWOW64** [comment]
@onein528 Please review (again)

**Review by onein528 — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
