### PR TITLE
General Updates 13

### LINKED ISSUE #186: Improve security of the authorization phase
### Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

DEBUG x64

### Description

I have an interesting theory:
Why don't we use the GH developer app for FH like we have used to on the store and delete AppCredentials.config so we can have a universal API key. This would remove the unnecessary method of the user creating an app and creating and entering the details in AppCredentials.config.
I would wish to try this, though it may cause security vulnerabilities that I have overlooked.

### Steps To Reproduce

_No response_

### Expected behavior

_No response_

### Relevant Assets

_No response_

### LINKED ISSUE #189: Implementation of IncrementalLoading
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

As the title

### Alternative solutions

_No response_

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by onein528**
### ⏱️ Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### ↗️ Related/Fixed issues

- Closes #186
- Closes #189

### 📄 Description

Official General Updates round 13

#### Todo

- [ ] Add click event to activities button in activities section in home page.
- [ ] Add click event to feed items in activities page.
- [ ] Handle OAuth Restriction exception properly.
- [ ] Completely update and improve indivisual issue/PR page.
- [ ] Add repository Insights page
- [ ] Add organization Peoples page
- [ ] Add organization Projects page
- [ ] Add filtering feature (reposityries, users, notifications, ...)
- [ ] Update indivisual Discussion page
- [ ] Update indivisual Project page
- [ ] Add repository Actions page
- [ ] Add search page
- [ ] Correct a word 'oction' to 'octicon'
- [ ] Fix activities page
- [ ] Add multilingual resources (en-US) English
- [ ] Add multilingual resources (en-UK) 'Real' English
- [ ] Add multilingual resources (es-ES) Spanish
- [ ] Add multilingual resources (ja-JP) Japanese
- [ ] Add multilingual resources (nl) Dutch

### 📸 Assets (if appropriate):

_None_

`React with a 👍 if you'd like to see this feature implemented`

### CODE REVIEW

**Comment by onein528** [comment]
New color codes:

GitHubDirkModeColors

```
#0d1017
#151b22
#21262e
#30373d
#484f58
#6e7681
#8b939e
#afbac5
#c9d1d9
#f0f6fc
#051d4d
#0d2d6b
#0d419d
#1158c7
#206feb
#388bfd
#58a6ff
#79c0ff
#a5d6ff
#cae8ff
#271051
#3c1e70
#553098
#6e40c9
#8957e5
#a371f7
#bc8cff
#d2a8ff
#e2c5ff
#edddff
#42062b
#5d103e
#7d2457
#9e3670
#bf4b8a
#db61a2
#f778ba
#ff9bce
#ffbedd
#ffdaec
#490402
#67090d
#8e1619
#b62324
#da3633
#f85149
#ff7b72
#ffa198
#ffc1ba
#ffdad5
#3d1300
#5a1e02
#752d09
#9b4216
#bd561d
#db6d28
#f0883e
#ffa657
#ffc680
#ffdeb3
#341a00
#4b2a00
#693e00
#825303
#9e6a03
#bb800a
#d29922
#e3b341
#f2cc60
#f8e3a1
#04260f
#053a15
#0f5322
#186c2e
#228636
#2ea043
#3fb950
#56d364
#7ee787
#aff5b4
```

**Comment by DeveloperWOW64** [comment]
> New color codes:

what are these for? @onein528

**Comment by onein528** [comment]
Coloring some places such as Issue/PR state labels, normal labels

**Comment by DeveloperWOW64** [comment]
> Coloring some places such as Issue/PR state labels, normal labels.
> 
> You don't agree?

idk. I suppose it might not be in accordance with the Microsoft Fluent Design System guidelines. @onein528

**Comment by onein528** [comment]
I know it. but are there colors of fluent design system?

**Comment by DeveloperWOW64** [comment]
> I know it. but are there colors of fluent design system?

@onein528 The AccentColour variables are fluent.

**Comment by onein528** [comment]
Open:
Close:
Draft:
Pending:
PRO:

there are many.

**Comment by onein528** [comment]
I think color color isn't important and what is important is how to display with those colors for uses.

**Comment by DeveloperWOW64** [comment]
> I think color color isn't important and what is important is how to display with those colors for uses.

sure then.

**Comment by DeveloperWOW64** [comment]
@onein528?

**Comment by onein528** [comment]
Can you build GU13?

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 Can you build GU13 instead of schema-gen branch?

Okay - done.. now the errors about Configuration Manager are done, but now I have these errors:
https://discord.com/channels/935562861701390336/982985508634366002/996302622946512927

**Comment by DeveloperWOW64** [comment]
@onein528

**Comment by onein528** [comment]
See this.

https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/#remove-parameter-null-checking-from-c-11

'paramerter null-checking' is no longer supported. it is removed in preview SDK.

We need to fix.

**Comment by DeveloperWOW64** [comment]
> 'paramerter null-checking' is no longer supported. it is removed in preview SDK.
> 
> We need to fix. Should be 'latest'

Okay - but wouldn't that only be a temporary fix? @onein528

**Comment by onein528** [comment]
I Updated csproj.

Then please build. if you cannot, tell me.

**Comment by DeveloperWOW64** [comment]
WOAH @onein528 Nice!
Fixed the error!
image

**Comment by DeveloperWOW64** [comment]
Changed a lot since I've last been able to run the app..

**Comment by onein528** [comment]
what exactly?

**Comment by DeveloperWOW64** [comment]
> what exactly?

@onein528 Sidebar, shell, etc. very nice!

**Comment by onein528** [comment]
image

**Comment by DeveloperWOW64** [comment]
@onein528 When will you implement localisation resources?

**Comment by onein528** [comment]
before merged this.

**Review by DeveloperWOW64 — COMMENTED** [review]
17adc2b8ccca123a1a831913412161c5762059c5
@onein528 Why change?

**Comment by onein528** [comment]
Simplified

**Comment by onein528** [comment]
All roght. Ready to add multilingual resources to some pages such as Intro Page.xaml

**Comment by DeveloperWOW64** [comment]
> All right. Ready to add multilingual resources to some pages such as Intro Page.xaml

Okay! Sadly I can only read spanish and not write so we'll have to wait for @BobbyESP. does @luandersonn know Brazilian Portugese?

**Comment by DeveloperWOW64** [comment]
> > All right. Ready to add multilingual resources to some pages such as Intro Page.xaml
> 
> Okay! Sadly I can only read spanish and not write so we'll have to wait for @BobbyESP. does @luandersonn know Brazilian Portugese?

@onein528

**Comment by onein528** [comment]
Yes! I will mention. I am going to prepare the default language, en-US.

**Comment by DeveloperWOW64** [comment]
@Gaoyifei1011 Can you do Chinese?

**Comment by Gaoyifei1011** [comment]
> @Gaoyifei1011 Can you do Chinese?

Yes, I can. I submitted a PR about Chinese Simplified translation a few months ago.

**Comment by DeveloperWOW64** [comment]
> Yes, I can. I submitted a PR about Chinese Simplified translation a few months ago.

Ah, I remember! But we've changed the UI so much it might not be valid anymore..

**Comment by DeveloperWOW64** [comment]
@onein528 You still working on multilingual resources?

**Comment by luandersonn** [comment]
> > All right. Ready to add multilingual resources to some pages such as Intro Page.xaml
> 
> Okay! Sadly I can only read spanish and not write so we'll have to wait for @BobbyESP. does @luandersonn know Brazilian Portugese?

Yes

**Comment by luandersonn** [comment]
> > Ohh guys. So sorry for being very inactive with this :( Img having some issues but dont worry. I can translate the app!
> 
> It's fine! @luandersonn has internship apparently so he is not online either. You will LOVE to see what's changed since you last built; the UI has improved so significantly!

You guys are doing a good work, well done

**Comment by DeveloperWOW64** [comment]
> Cannot add resources...

Why? Option is greyed out?
@onein528

**Comment by onein528** [comment]
YES

**Comment by DeveloperWOW64** [comment]
> I have seen that before.. so weird

I will investigate.

**Comment by DeveloperWOW64** [comment]
@onein528 When clicking on activities/marketplace (buttons I added) they don't fill with the accent colour
image
also, activities gives NullReferenceException.

**Comment by onein528** [comment]
Should I delete those button? I think it doesnt make any sense.

**Comment by DeveloperWOW64** [comment]
> Should I delete those button? I think it doesnt make any sense.

@onein528 Why? Marketplace is queryable and Activities cannot go underneath the recent feed as it is different info. Build the app to see changes in a4b088b81f5f221adae9d29dd78b9971450c3c6b.

**Comment by onein528** [comment]
No I think I should remove all buttons

image

**Comment by DeveloperWOW64** [comment]
> No I think I should remove all buttons

But what would we do then? Personally I disagree.

**Comment by onein528** [comment]
Right.
I have to create new Actovity page then?

**Comment by DeveloperWOW64** [comment]
> Right. I have to create new Actovity page then?

Create a new one? Why?

**Comment by DeveloperWOW64** [comment]
> Create a new one? Why?

@onein528

**Review by ioapiset — APPROVED** [review]
LGTM.

**Pull request merged**
