### PR TITLE
Added a new collaborator to About page

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [ ] Have you built and ran the app?

###### <sup>Address related/fixed issues</sup>

None

###### <sup>Details of changes are listed here</sup>
Added @DeveloperWOW64 as contributor and updated @onein528's name

###### <sup>Items resolved/related issues by this PR.</sup>
None

###### <sup>A list of assets (screenshots, mockups) relevant to this pull request.</sup>
None

### CODE REVIEW

**Review by onein528 — APPROVED** [review]
LGTM. you customized your avator, but it will be replaced by GitHub Collaborators API.

**Comment by DeveloperWOW64** [comment]
> LGTM. you customized your avator, but it will be replaced by GitHub Collaborators API.

ok

**Comment by DeveloperWOW64** [comment]
> LGTM. you customized your avator, but it will be replaced by GitHub Collaborators API.

What do you mean by this?
are you planning to put in the GH Collab API?

**Comment by onein528** [comment]
Yes.

**Comment by onein528** [comment]
In addition to introducing the GitHub API to the account page of the settings, we will also introduce it to the About page.

**Pull request merged**
