### PR TITLE
Updating IntroPage.xaml

### PR DESCRIPTION
**Pull request by nathayoung**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

###### <sup>Address related/fixed issues</sup>

- Related: #114 
- Fixed: #

###### <sup>Details of changes are listed here</sup>
Formatted previous work already done in #114 to reach the goal mentioned in the comments. 

###### <sup>A list of assets (screenshots, mockups) relevant to this pull request.</sup>
image

### CODE REVIEW

**Comment by onein528** [comment]
Can you fetch?

**Comment by onein528** [comment]
Have/will you commit more?

**Comment by onein528** [comment]
This build fail is not error of source code just our problem when merging from forked repo.

image

**Comment by nathayoung** [comment]
> Have/will you commit more?

Maybe.  I did that instead of my homework last night so I can't say I'll be consistent, but if you need/want xaml help, I can chip in.  I've done a lot with html and xaml isn't too far away.

**Review by onein528 — APPROVED** [review]
LGTM. Thank you!
This is your first time contributing.

**Pull request merged**
