### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by onein528**

### CODE REVIEW

**Comment by DeveloperWOW64** [comment]
WOAH @onein528 Multilingual App Toolkit works??

**Review by DeveloperWOW64 — APPROVED** [review]
OK wow @onein528 Well done! Works fine.

**Comment by onein528** [comment]
> WOAH @onein528 Multilingual App Toolkit works??

No, added en-us manually and crowd in automatically added others.

**Comment by DeveloperWOW64** [comment]
> > WOAH @onein528 Multilingual App Toolkit works??
> 
> @DeveloperWOW64 No, added en-us manually and crowdin in automatically added others.

So how will you be able to actually *use* the resources?

**Comment by onein528** [comment]
Using resource extension. I will add few resources for example.

**Pull request merged**
