### PR TITLE
PR & Issue Templates

### PR DESCRIPTION
**Pull request by DeveloperWOW64**

### CODE REVIEW

**Comment by onein528** [comment]
Nice update. but one thing what I forgot to tell you: please don't merge your own PR.

You:
1. Create a PR
2. Change some
3. Label "needs review" when finished

Other member:
1. Review changes deeply
2. If apprived, add "approved" label and remove all label.

**Comment by DeveloperWOW64** [comment]
> 

oh okay thanks!

**Review by onein528 — COMMENTED** [review]
LGTM

**Comment by onein528** [comment]
Thank you!

**Comment by DeveloperWOW64** [comment]
> Thank you!

全銭いいよ！

**Comment by onein528** [comment]
Actually 全然 is right. haha

**Comment by DeveloperWOW64** [comment]
> Actually 全然 is right. haha

@onein528 As in it's actually 全然 instead of ぜんぜんいいよ？

**Comment by onein528** [comment]
no. "全然いいよ！" is right

**Comment by DeveloperWOW64** [comment]
> Actually 全然 is right. haha

oh. then WDYM?

**Comment by onein528** [comment]
```diff
-全銭いいよ！
+全然いいよ！
```

kanji is broken.

**Comment by DeveloperWOW64** [comment]
> ```diff
> -全銭いいよ！
> +全然いいよ！
> ```
> 
> kanji is broken.

bruh

**Comment by onein528** [comment]
'銭' means money. 全 means 'all'

全銭 means... all money? ahah
全然 means "no problem at all"

**Comment by onein528** [comment]
but nice japanese skill! improving day by day

**Comment by DeveloperWOW64** [comment]
> but nice japanese skill! improving day by day

ありがとう！ I have a streak of 10 days for practicing.

**Comment by onein528** [comment]
and commit title should start with the past verb.

forexample,

Updated PR and issue templates
Added
Unified
Improved
Reverted

**Comment by DeveloperWOW64** [comment]
> and commit title should start with the past verb.
> 
> forexample,
> 
> Updated PR and issue templates Added Unified Improved Reverted

Really? @onein528 I always thought GH commit standard was in present tense, not past.

**Comment by onein528** [comment]
Right. I’ve committed to Git with this rule always. However whichever is good. We may have to create commit message rule

**Comment by DeveloperWOW64** [comment]
> Right. I’ve committed to Git with this rule always. However whichever is good. We may have to create commit message rule

Present tense is GH standard:
image
When you create a new file and put in no commit message, it will auto-generate one in *present tense*

**Comment by onein528** [comment]
As a native speaker of English, which is better?

**Comment by DeveloperWOW64** [comment]
> As a native speaker of English, which is better?

@onein528 Present tense.

**Comment by onein528** [comment]
Good I'll use that

**Pull request merged**
