### PR TITLE
Number normalizer

### PR DESCRIPTION
**Pull request by hunterlan**
### ⏱️ Before you start

- [х] Have you checked if a similar PR has already been requested? 
- [х] Have you built and ran the app?

### ↗️ Related/Fixed issues

- Related: #246 
- Fixed: #246 

### 📄 Description

Added number normalizer helper. It's static class, which can be used everywhere.
Also, I changed a bit repository overview.

### 📸 Assets (if appropriate):

image

### CODE REVIEW

**Review by DeveloperWOW64 — CHANGES_REQUESTED** [review]
@hunterlan This is a bit fussy, but can you fix [this](https://github.com/FluentHub/FluentHub/pull/250/files#annotation_4484595926)?

**Comment by hunterlan** [comment]
> @hunterlan This is a bit fussy, but can you fix [this](https://github.com/FluentHub/FluentHub/pull/250/files#annotation_4484595926)?

no problem!

**Review by DeveloperWOW64 — APPROVED** [review]

**Comment by onein528** [comment]
Already been merged tho, LGTM.

**Comment by onein528** [comment]
I've meant to use library such as DataSizeUnits.

**Comment by onein528** [comment]
@DeveloperWOW64 We should've used something library for this such as 'DataSizeUnits'.

**Comment by hunterlan** [comment]
> @DeveloperWOW64 We should've used something library for this such as 'DataSizeUnits'.

Why? It's not necessary, current convertor is working well

**Comment by onein528** [comment]
Yeah. Of course, Thank you for your contribution. But I didn't want to use helpers but converters. The reason why is easy to convert value on XAML code.

**Comment by onein528** [comment]
It is not necessary to add observable strong properties for converted values. Converters on XAML is just able to be converted as you expected with no properties.

**Pull request merged**
