### PR TITLE
General Updates 11

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

*- GH Desktop, the program I use, got confused while creating the branch and instead restored the old GU10 branch - this shouldn't cause major problems though -*

###### <sup>A list of assets (screenshots, mockups) relevant to this pull request.</sup>

Some of the changes:
image

### CODE REVIEW

**Comment by onein528** [comment]
Can you this be 11?

**Comment by DeveloperWOW64** [comment]
> Can you this be 11?

Ok - doing it now

**Comment by onein528** [comment]
https://github.com/FluentHub/FluentHub/pull/127 this may be 10. I dont know but very extensive changes.

**Comment by onein528** [comment]
Sorry.

**Comment by DeveloperWOW64** [comment]
I'll create a new PR and port the changes - GH Desktop is very confused

**Pull request closed without merging**
