### PR TITLE
Update Search Bar

### PR DESCRIPTION
**Pull request by DeveloperWOW64**

### CODE REVIEW

**Comment by DeveloperWOW64** [comment]
Oops accidentally used GU17 branch..

**Comment by onein528** [comment]
I really liked TeachingTip. Why did you change?

**Comment by DeveloperWOW64** [comment]
> I really liked TeachingTip. Why did you change?

@josephbeattie said.

**Comment by DeveloperWOW64** [comment]
@onein528 What do you like about the TeachingTip so much?

**Comment by onein528** [comment]
I think it is really cool idea.

**Comment by DeveloperWOW64** [comment]
Should I ask the community, or do you want to make an administrative decision? @onein528

**Comment by onein528** [comment]
Let's ask the community

**Comment by onein528** [comment]
Can you take a screenshot whole window?

**Review by mousemaid — APPROVED** [review]
Approved on behalf of the community.

**Comment by DeveloperWOW64** [comment]
> Can you take a screenshot whole window?

Ok. I just need to switch branch.

**Comment by DeveloperWOW64** [comment]
> Can you take a screenshot whole window?

@onein528
Prior to click:
image

After click:
image

**Comment by DeveloperWOW64** [comment]
@onein528

**Review by onein528 — APPROVED** [review]
Looks Great to me!

**Pull request merged**
