### PR TITLE
Adding various data searching function

### PR DESCRIPTION
**Pull request by arihant2math**
### ↗️ Related/Fixed issues

- Related: #253
- Fixed: #264

### 📄 Description

Adds a search page.

### Motivation and context

- [x] Implement Search data retrieval for repos
- [x] Implement Search data retrieval for users
- [x] Implement Search data retrieval for code
- [x] Implement Search data retrieval for issues
- [ ] Implement Getting instances of search query in code
- [x] Implement Search data templates for repos
- [x] Implement Search data templates for users
- [ ] Implement Search data templates for code
- [x] Implement Search data templates for issues
- [ ] Implement Search data templates for prs
- [x] Implement Search data presentation for repos
- [x] Implement Search data presentation for users
- [ ] Implement Search data presentation for code
- [x] Implement Search data presentation for issues
- [ ] Implement Search data presentation for prs
- [x] Implement repos search page
- [x] Implement users search page
- [x] Implement code search page
- [x] Implement issues search page
- [ ] Implement Context Based Searching and Jump To
- [ ] Fix Ctrl+/ keyboard accelerator [Need Help]

### 📸 Assets (if appropriate):

image

image

### CODE REVIEW

**Comment by arihant2math** [comment]
@onein528 @DeveloperWOW64 I'll need help with the Data Templates because I'm not experienced with XAML. I would be needing data templates for issues, code, users, and repos.

**Comment by arihant2math** [comment]
Half way there!

**Comment by onein528** [comment]
I couldnt review right now. but i will definitely do asa possible

**Comment by arihant2math** [comment]
No worries, I still have quite a lot of work to do, most of it is quite difficult.

**Comment by onein528** [comment]
you seem that some search result model files are created in v4 namespace. but please move v3 folder. v4 folder is for graphql api and updated those models by generator and models that created manually will be deleted by generator.

**Comment by onein528** [comment]
your changes are quite cool. i will commit some more updates.

**Comment by arihant2math** [comment]
> you seem that some search result model files are created in v4 namespace. but please move v3 folder. v4 folder is for graphql api and updated those models by generator and models that created manually will be deleted by generator.

I understand, I will move them in my next commit.

**Comment by arihant2math** [comment]
Repo Search is operational:
image

**Comment by onein528** [comment]
LOVE IT! I LOVE IT! cool.

**Comment by onein528** [comment]
@arihant2math I'm working on this. Please note that my changes would be a breaking change.

**Comment by arihant2math** [comment]
I'm going to finish it up, do you mind waiting for a bit (I'll be doing what I did to repos to the rest of the pages)

**Comment by onein528** [comment]
Ah, I got already started. But I can. Before doing so, can you solve merge conflicts?

**Comment by onein528** [comment]
@arihant2math

**Comment by arihant2math** [comment]
@onein528 
> Ah, I've got already started. But, not at all, I can.

You can put your changes on a branch and wait for a bit and then fix merge conflicts. 

> Before doing so, can you solve merge conflicts?

I created the fork via gh so I can't do it via terminal and gh isn't allowing me to do it via the gui (its telling me that I either need write access or I have to discard all my commits). Do you know the relevant git commands to use?

**Comment by arihant2math** [comment]
Updates:
image
image

**Comment by onein528** [comment]
Are you not be displayed this?

image

If not, you can use them:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

**Comment by onein528** [comment]
I couldn't commit my change into this branch. Did yoy enabled 'Allow edits from maintainers.' when creating PR?

**Comment by arihant2math** [comment]
Screen Shot 2022-09-22 at 8 52 08 PM
You would need to resolve them because I need write access.

Maintainers can now edit.

However, while I am very excited about the pr, this pr is very much still a draft and I don't think this should be merged until I fix some of the inherently visible problems with the issues page which are due to the search query not returning all the necessary info. Furthermore the code search has not been implemented yet, because I just started implementing displaying yesterday, and due to some complications it will take a day or two.

**Comment by onein528** [comment]
i can give you write access for a while

**Comment by onein528** [comment]
> Also, do you know where I can find the glyph values for the octicons? I can only find the name not the hex.

Install octicon and see glyph map in CharacterMapUwp

**Comment by onein528** [comment]
> You would need to resolve them because I need write access.
> Maintainers can now edit

image

Thanks. I will take a look.

**Comment by onein528** [comment]
What. What? I merged this by mistake with meaningless commit title.............. I AM SORRY.

**Comment by onein528** [comment]
I'll write this PR in README credit section.

**Comment by onein528** [comment]
@arihant2math I reverted it. Can you re-open PR with this fork branch?

**Pull request merged**
