### PR TITLE
Fix Azure Pipelines

### PR DESCRIPTION
**Pull request by onein528**
### ⏱️ Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### 💭 Motivation and context

- Fixed: #324 

### 📄 Description

_None_

### 📸 Assets (if appropriate):

_None_

### CODE REVIEW

**Comment by onein528** [comment]
Hmmm... It seems that we should package FluentHub with packaging project.

**Comment by onein528** [comment]
https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/ci-for-winui3?pivots=winui3-packaged-csharp

**Comment by onein528** [comment]
Current status:

- Fixed Debug pipeline
- Fixed Sideload pipeline
- Yet have fixed StoreUpload pipeline

**Review by ioapiset — APPROVED** [review]

**Pull request merged**
