### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by onein528**

### CODE REVIEW

**Comment by onein528** [comment]
How can I fix this....

**Comment by arihant2math** [comment]
@onein528 What do you mean?

**Comment by DeveloperWOW64** [comment]
> @onein528 What do you mean?

Merge conflicts.

**Comment by onein528** [comment]
I will copy entire https://github.com/FluentHub/FluentHub/tree/l10n_main/src/FluentHub.Uwp/Strings to https://github.com/FluentHub/FluentHub/tree/main/src/FluentHub.App/Strings

**Comment by onein528** [comment]
Brought those changes into main directly.

**Pull request closed without merging**
