### PR TITLE
General Updates 10

### PR DESCRIPTION
**Pull request by onein528**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

###### <sup>Address related/fixed issues</sup>

- Fixes: #138 
- Fixes: #169

###### <sup>Details of changes are listed here</sup>

General updates round 10

###### <sup>A list of assets (screenshots, mockups) relevant to this pull request.</sup>

None yet

### CODE REVIEW

**Comment by onein528** [comment]
@DeveloperWOW64 Do you think which [stable + heavy = v3 API] or [unstable + fast v4 API] is better to use?

**Comment by onein528** [comment]
stable + heavy = v3 API will not occur this issue but heavy sometimes.

**Comment by DeveloperWOW64** [comment]
> stable + heavy = v3 API will not occur this issue but heavy sometimes. try?

Try it.

**Comment by onein528** [comment]
good. i will replace some quries with v3

**Comment by DeveloperWOW64** [comment]
Good. If FH gets really slow we can always try v4

**Comment by onein528** [comment]
Trying to

image

**Review by DeveloperWOW64 — CHANGES_REQUESTED** [review]
3 things to be done:
- Add the v4 api. v3 is slow when navigating through repos - this is debatable
- Add a button in settings underneath here called 'Refresh Access' that leads the user to https://github.com/settings/developers so that they can give the app access to any new orgs they've made/joined.

image
- FH doesn't display the repos for an org unless the org has them pinned on their profile.

image

**Comment by onein528** [comment]
maybe figure #169 out. i create class as universal windows lib but may need to create as .net standard app.

**Comment by DeveloperWOW64** [comment]
> maybe figure #169 out. i create class as universal windows lib but may need to create as .net standard app.

WDYM? which one are you talking about? the one with no repos?

**Comment by onein528** [comment]
never mind. i tell you later.

**Comment by onein528** [comment]
currently, working on #169.

> FH doesn't display the repos for an org unless the org has them pinned on their profile.

that called OAuth Restriction #95

I could not fix this except if this project uses OAuth App.

**Comment by onein528** [comment]
> Add the v4 api. v3 is slow when navigating through repos - this is debatable
Add a button in settings underneath here called 'Refresh Access' that leads the user to https://github.com/settings/developers so that they can give the app access to any new orgs they've made/joined.

good enhancement.

**Comment by onein528** [comment]
can you tell me more details about first one? @DeveloperWOW64

**Comment by DeveloperWOW64** [comment]
> can you tell me more details about first one? @DeveloperWOW64

I tested the API by navigating through fluenthub/fluenthub and found that it kept loading the further i went.

**Comment by onein528** [comment]
i dont use v3 api on all repo pages(overview, code, issue, pr,...).

I know you want to say this: https://github.com/FluentHub/FluentHub/blob/main/src/FluentHub.Octokit/Queries/Repositories/CommitQueries.cs

get a commit when queried each object. so it will be slow.

**Comment by DeveloperWOW64** [comment]
> i dont use v3 api on all repo pages(overview, code, issue, pr,...).
> 
> I know you want to say this: https://github.com/FluentHub/FluentHub/blob/main/src/FluentHub.Octokit/Queries/Repositories/CommitQueries.cs#L113-L176
> 
> get a commit when queried each object. so it will be slow.

I didnt realise that

**Comment by DeveloperWOW64** [comment]
> i dont use v3 api on all repo pages(overview, code, issue, pr,...).
> 
> I know what you want to say: https://github.com/FluentHub/FluentHub/blob/main/src/FluentHub.Octokit/Queries/Repositories/CommitQueries.cs#L113-L176
> 
> get a commit when queried each object. so it will be slow.

What pages do you use v3 on?

**Comment by onein528** [comment]
NotificationsViewModel, ActivitiesViewModel, Readme queries(there are no such api on v4).

Search "App.Client" on entire solution

**Comment by DeveloperWOW64** [comment]
> NotificationsViewModel, ActivitiesViewModel, Readme queries(there are no such api on v4).
> 
> Search "App.Client" on entire solution

I'll have a look later and code a bit - I'm doing something rn

**Comment by onein528** [comment]
greate changes in b80fd4f

re-configured FluentHub.Core and FluentHub.Octokit project from Universal Windows to .NET standard

**Comment by onein528** [comment]
Revert all changes. I am not familiar with .NET environment.

**Comment by DeveloperWOW64** [comment]
> Revert all changes. I am not familiar with .NET environment.

🤣

**Pull request closed without merging**
