### PR TITLE
Report Templates v2

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
### Before you start

- [ ] Have you checked if a similar PR has already been requested? 

###### <sup>Address related/fixed issues</sup>

- Related: #
- Fixed: #

### CODE REVIEW

**Review by onein528 — APPROVED** [review]
Good

**Comment by onein528** [comment]
Mergeable?

**Comment by DeveloperWOW64** [comment]
> Mergeable?

I think.. there doesnt seem to be anything else I can do

**Comment by onein528** [comment]
on this PR or entire this project?

**Comment by DeveloperWOW64** [comment]
> on this PR or entire this project?

oh on this PR definitely

**Comment by DeveloperWOW64** [comment]
but yeah please merge
@onein528

**Pull request merged**
