### PR TITLE
FluentHub Push UI

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
###### <sup>Address related/fixed issues</sup>

#185

###### <sup>Details of changes are listed here</sup>

This is a massive WIP PR that covers the UI for FluentHub Push.
Do not expect this to be done soon.

### CODE REVIEW

**Comment by DeveloperWOW64** [comment]
test msg

**Comment by DeveloperWOW64** [comment]
ye i have no idea how to do this i am only good at UI. I thought we could copy code from GH Desktop but it is an electron app and has a completely different framework to .NET.

**Comment by onein528** [comment]
wait a week.

**Comment by DeveloperWOW64** [comment]
> wait a week.

WDYM? why?

**Comment by onein528** [comment]
what do you want to implement? there's a concept, mock-up, or screenchot?

**Comment by DeveloperWOW64** [comment]
> what do you want to implement? there's a concept, mock-up, or screenchot?

image
@onein528

**Comment by DeveloperWOW64** [comment]
> what do you want to implement? there's a concept, mock-up, or screenchot?

Or light mode:
image
@onein528

**Comment by DeveloperWOW64** [comment]
@onein528 They're by Zeealeid. I asked him for permission to use them, and he said yes.
https://twitter.com/DeveloperWOW64/status/1538941281367429122

**Comment by DeveloperWOW64** [comment]
> @onein528 They're by Zeealeid. I asked him for permission to use them, and he said yes. https://twitter.com/DeveloperWOW64/status/1538941281367429122

oh wait lol
image

**Comment by onein528** [comment]
I don't know. You want to integrate gh desktop and gh website?

**Comment by onein528** [comment]
Want to access the local git folder?

**Comment by onein528** [comment]
nvm. just want to access to local git folder to push the diff changes?

**Comment by onein528** [comment]
oookay... this will be a big feature

**Comment by DeveloperWOW64** [comment]
> oookay... this will be a big feature

@onein528 yep..

**Comment by onein528** [comment]
and need to discuss lots of thing before being opened PR. please close this.

**Pull request closed without merging**
