### PR TITLE
Crowdin Updates

### PR DESCRIPTION
**Pull request by DeveloperWOW64**

### CODE REVIEW

**Comment by onein528** [comment]
Nooooooo.... Crowd in uses constantly ‘l10n’ branch.

**Comment by DeveloperWOW64** [comment]
> Nooooooo.... Crowd in uses constantly ‘l10n’ branch

whhhhhhyyyyyyyyyy crowdin ok i can use l10n_main branch but everytime a PR is merged i need to make sure it is fully deleted.

**Comment by onein528** [comment]
Then you dont need to check out to "l10n_main". Just do stuff on GitHub.

**Comment by onein528** [comment]
Could it be you update resources on your local machine directly?

**Comment by DeveloperWOW64** [comment]
> Could it be you update resources on your local machine directly?

sure.

**Comment by onein528** [comment]
ahm, I didnt mean to like that. Did you update resources on your local machine(without Crowdin site)?

**Comment by DeveloperWOW64** [comment]
> ahm, I didnt mean to like that. Did you update resources on your local machine(without Crowdin site)?
> 
> I think those commits weren't created by Crowdin.
> 
> image

Yep. On my local machine.

**Pull request closed without merging**
