### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by bennett-sh**
### ⏱️ Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### 📄 Description
I fixed a typo in the README.

### CODE REVIEW

**Review by DeveloperWOW64 — APPROVED** [review]
@bennett-sh Thank you for your contribution!

**Comment by onein528** [comment]
azp /run

**Comment by DeveloperWOW64** [comment]
> azp /run

@onein528 FYI it's
/azp run

**Comment by DeveloperWOW64** [comment]
lool

**Comment by DeveloperWOW64** [comment]
Perhaps workflows don't run after a pr is closed.

**Comment by onein528** [comment]
Ok. I will run on Azure Pipeline manually.

**Pull request merged**
