### PR TITLE
Remove the rounded white background of the logos

### PR DESCRIPTION
**Pull request by DeveloperWOW64**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

###### <sup>Details of changes are listed here</sup>

Removes ugly background of the icons.

###### <sup>A list of assets (screenshots, mockups) relevant to this pull request.</sup>

image

### CODE REVIEW

**Comment by onein528** [comment]
nice. but i have svg and can update without no background

**Comment by DeveloperWOW64** [comment]
> nice. but i have svg and can update without no background

WDYM?

**Comment by onein528** [comment]
I have raw SVG file of this avatar. So I can generate icons with no background.

**Comment by DeveloperWOW64** [comment]
> I have raw SVG file of this avatar. So I can generate icons with no background.

Cool!

**Comment by DeveloperWOW64** [comment]
> I have raw SVG file of this avatar. So I can generate icons with no background.

Can you do this please?

**Comment by onein528** [comment]
Yep.

**Comment by DeveloperWOW64** [comment]
@onein528 Why'd you suspend this PR?

**Comment by onein528** [comment]
I want to do this. but I have no time to improve logos...
But here's svg: https://github.com/FluentHub/FluentHub-Logo/tree/main/Primitives-20220513

I am sorry.

**Comment by DeveloperWOW64** [comment]
> I want to do this. but I have no time to improve logos... But here's svg: https://github.com/FluentHub/FluentHub-Logo/tree/main/Primitives-20220513
> 
> I am sorry.

But I've already done it: this PR is mergeable

**Comment by onein528** [comment]
The reason for the white background is to accommodate any color taskbar or start menu. In particular, it prevents the logo from obscuring the eye and the border. Do you not have this concern?

**Comment by DeveloperWOW64** [comment]
> The reason for the white background is to accommodate any color taskbar or start menu. In particular, it prevents the logo from obscuring the eye and the border. Do you not have this concern?

No. Personally, the logo has enough contrast and the white border is against the Windows App Icon schema.

**Comment by onein528** [comment]
right.

**Comment by DeveloperWOW64** [comment]
> right.

What do you think? Is it worth it?

**Review by onein528 — APPROVED** [review]
LGTM. thank you!

**Pull request merged**
