### PR TITLE
Improve app launch performance

### PR DESCRIPTION
**Pull request by itsWindows11**
This PR aims to speed up app launch by making splash screen optional and enabling prelaunch if needed, on debug mode there might be no differences but on release mode it works.

### CODE REVIEW

**Comment by onein528** [comment]
Thank you for your proposal.

We have decided not to publish the app packages with RELEASE config to the ms store and GitHub Releases page

**Comment by onein528** [comment]
In release mode app, System.Linq.Select() is not supported. It seems that it is missing from app container.

**Comment by itsWindows11** [comment]
I guess either disable .NET Native in the config or fork the library and fix it.

**Comment by dongle-the-gadget** [comment]
Isn't .NET Native required?

**Comment by itsWindows11** [comment]
> Isn't .NET Native required?

In what context?

**Comment by itsWindows11** [comment]
Oh, idk they said the version currently published in the store has this one Select() problem.

**Comment by onein528** [comment]
This PR really improve launch performance?

**Comment by onein528** [comment]
My previous offer: `https://github.com/files-community/Files/issues/3356`

**Comment by itsWindows11** [comment]
> To do.
> 
> Fix: merge conflicts
> Question: This PR really improve launch performance?

I'll make a comparison video when I have time

**Comment by itsWindows11** [comment]
@onein528 Here's the comparison video for both debug and release mode on my PC:

https://user-images.githubusercontent.com/81253203/182339649-781c868d-9f4f-4874-a634-72d9634aca82.mp4

**Review by onein528 — APPROVED** [review]
LGTM. Thank you! 🚀

**Pull request merged**
