### PR TITLE
Fix: Check events before accessing them #155

### PR DESCRIPTION
**Pull request by GermanAizek**
### Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### Related/Fixed issues
- Related: None
- Fixed: None

### Description
Checks for events before accessing them, prevents NullReferenceException

### CODE REVIEW

**Comment by onein528** [comment]
These changes were built successfully?

**Comment by GermanAizek** [comment]
@onein528, msvc 2022, target version Windows 11 SDK build 22000
Build succesful.

**Comment by onein528** [comment]
@DeveloperWOW64 Want your review!

**Comment by onein528** [comment]
I'm gonna wait even if this changes are build successfully until azure pipelines are available.

**Comment by GermanAizek** [comment]
@DeveloperWOW64, in this pr commit https://github.com/FluentHub/FluentHub/pull/157/commits/6384c0038e2ac854461b3ec2d373f2032729d6df, I have already removed these changes
```
NotificationQueries.cs

|ln:101| Convert.ToInt32(urlItems[urlItems?.Count() - 1]));
                                          ^ Why is there a question mark here? It's causing errors
|ln:122| Convert.ToInt32(urlItems[urlItems?.Count() - 1]));
                                          ^ Why is there a question mark here? It's causing errors
```
I have my branch built without them

**Comment by GermanAizek** [comment]
@DeveloperWOW64, why this pull request has `+0 −0` changes? Do you want to merge past changes with an error?
If so, it is enough to correct these lines https://github.com/FluentHub/FluentHub/pull/157#issuecomment-1136898422

**Comment by onein528** [comment]
@GermanAizek Sorry i reverted.. Can yoou re-change? I am sorry..

**Comment by GermanAizek** [comment]
> Sorry i reverted.. Can yoou re-change? I am sorry..

@onein528, ok wait.

**Comment by GermanAizek** [comment]
@onein528, done.
https://github.com/FluentHub/FluentHub/pull/157/commits/4c15cb1010d784c0b8fbf94408cd2bfcbdf8b725

**Comment by GermanAizek** [comment]
@onein528, I did not have such a error
Pipeline output:
```
Error MSB3030: Could not copy the file "D:\a\1\s\src\FluentHub\AppCredentials.config" because it was not found.
```

**Comment by onein528** [comment]
Good. FYI, when trigged pipeline by forked repo, it will fail. so don't worry.

**Review by onein528 — APPROVED** [review]
LGTM. Thank you, then I will merge.

**Pull request merged**
