### PR TITLE
Fixed NullRederenceException in the Activities page

### PR DESCRIPTION
**Pull request by hunterlan**
### ⏱️ Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### ↗️ Related/Fixed issues

No related issues.

### 📄 Description

Now, activities is shown on page.

### 💭 Motivation and Context

I added initialization for properties, where it should be.

Fixed null exceptions, when getting activites. 

### 📸 Assets (if appropriate):

Before: 
image

After:
image

### CODE REVIEW

**Review by onein528 — APPROVED** [review]
LGTM.
You're the first-time contributor and even first-time contributor to FluentHub core feature! Thank you!

**Comment by onein528** [comment]
@hunterlan This PR should close #210?

**Comment by hunterlan** [comment]
> @hunterlan This PR should close #210?

No, IT shouldn't. You said, you'll take it, so, I started to discover the source code and fixed bug (and will fix others, if they exist).

**Comment by onein528** [comment]
Got it. When I fixed activities page totally, publish new version and tell you.

**Comment by hunterlan** [comment]
> By the way, Mergeable?

Should be. GitHub says, it's ready to merge

**Comment by hedhehd** [comment]
I thought for a second that this is gonna fix #210

**Comment by hedhehd** [comment]
But I was wrong

**Comment by hunterlan** [comment]
> I thought for a second that this is gonna fix #210

No, but this is also important fix.

**Comment by onein528** [comment]
Thank you! @hunterlan

**Comment by hunterlan** [comment]
> Thank you! @hunterlan 

You're welcome :)

**Pull request merged**
