### PR TITLE
Update FluentHub intro page

### PR DESCRIPTION
**Pull request by BobbyESP**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Closes 

### Details of Changes

- Added a new login page

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

### CODE REVIEW

**Comment by onein528** [comment]
can you tell us what you changed as screenshot

**Comment by BobbyESP** [comment]
I made the PR before my mom told me to go bed haha. Just see JitHub login and you can make an idea. I'll modify it but by the moment im just copying

**Comment by onein528** [comment]
ok. good night

**Comment by BobbyESP** [comment]
Thanks, guys! I'll be working on this when i finish my exams the day 6 of June, sorry!

**Comment by onein528** [comment]
Niceee!

**Comment by DeveloperWOW64** [comment]
I'm thinking there are two designs we should go for:
a) The one seen in MS PowerToys:
image
Picture of FluentHub in the background and then FluentHub's own logo, with a button leading to docs and source code.
'Open Settings' replaced with 'Get started'

b) The one seen in MS Get Started:
image
Say something like:
## Hi!

###### Let's get started and see what FluentHub can do.
[Start]

Then it would lead on to explain the features of FluentHub (with a skip bar in the bottom) and after that it would go to SignInPage.xaml.

My favourite one is probably option b but I'm up to ideas

**Comment by onein528** [comment]
I've already seen those start pages(explorered when I created current sign in page to get a lot of ideas) even all ms or other 3rd-p apps that I know.
Is current sign in page frugal? I think it's better not to update page design.

**Comment by onein528** [comment]
But it is very frugal, I think. so very like adding background, buttons(leads to our GH site or sth), and "getting start" messages.

**Comment by DeveloperWOW64** [comment]
While the Get Started one looks better, the PowerToys one looks easier to code. I'll see if I can code the PT one and then see if I like it

 - School has taken a lot of time from me - luckily i've got a holiday for just over a week so I can spend more time in FluentHub. But because I'm in the UK, you're 8 hrs ahead of me 😬.

**Comment by BobbyESP** [comment]
Ouu, sorry 🙌 . I wanted to say that in the account switching, but if you want me to work in this, i will able too.

**Comment by DeveloperWOW64** [comment]
> Ouu, sorry 🙌 . I wanted to say that in the account switching, but if you want me to work in this, i will able too.

Yes please!

I'm working on a one like this:
image

I've just made a hero image - 
OOBEHERO

See what you can do and then commit to this branch so I can see and edit!

**Comment by BobbyESP** [comment]
> > Ouu, sorry 🙌 . I wanted to say that in the account switching, but if you want me to work in this, i will able too.
> 
> Yes please!
> 
> I'm working on a one like this: image
> 
> I've just made a hero image - OOBEHERO
> 
> See what you can do and then commit to this branch so I can see and edit!

Ok nice!

**Comment by onein528** [comment]
Got it. I am deving on GU10 branch.

**Comment by onein528** [comment]
> While the Get Started one looks better, the PowerToys one looks easier to code. I'll see if I can code the PT one and then see if I like it
> 
> 
> 
>  *- School has taken a lot of time from me - luckily i've got a holiday for just over a week so I can spend more time in FluentHub. But because I'm in the UK, you're 8 hrs ahead of me 😬. -*
> 
> 
> 
> 

Good. GMT+9 I am. also my time am taken by school ha

**Comment by DeveloperWOW64** [comment]
### 🔨 Coming along!!

image

**Comment by onein528** [comment]
Good enough!!

**Comment by DeveloperWOW64** [comment]
> Good enough!!

I do wish it would fill the pic would fill the whole window like in this:
image

I just dont know how to make it do that without looking ugly

**Comment by onein528** [comment]
> ### 🔨 Coming along!!
> image

Can you give me this background image?

**Comment by DeveloperWOW64** [comment]
> Can you give me this background image?

https://user-images.githubusercontent.com/71598437/170543271-52a444d0-a0ec-40a6-8455-ce86226fa0c3.png

**Comment by nathayoung** [comment]
Like this? 
image

**Comment by BobbyESP** [comment]
Yes! It's nice!

**Comment by onein528** [comment]
Yes!!

**Comment by nathayoung** [comment]
Can I have access to commit that or do you want me to open a new PR? @onein528

**Comment by onein528** [comment]
yea, open please.

**Comment by DeveloperWOW64** [comment]
Loving the new look! 🤣🤣
image
I'll do some fixing (I'm back from holiday)

**Comment by nathayoung** [comment]
> Loving the new look! 🤣🤣
> image
> I'll do some fixing (I'm back from holiday)

Well it didn't look like that on my pc 😂. I guess relative sizing should be a thing lol

**Comment by DeveloperWOW64** [comment]
done

**Comment by onein528** [comment]
@BobbyESP @DeveloperWOW64 @nathayoung Can I merge this into GU12?

**Comment by BobbyESP** [comment]
I say Yes, but let Jupiter tell if he wants to merhe or not

**Comment by DeveloperWOW64** [comment]
> @BobbyESP @DeveloperWOW64 @nathayoung Can I merge this into GU12?

Just what I was thinking.

**Review by onein528 — APPROVED** [review]
LGTM. Thank you!

```diff
+ Updated messages when no items available.
+ Updated app's oobe page
```

**Comment by DeveloperWOW64** [comment]
oops

**Comment by DeveloperWOW64** [comment]
@onein528 merge?

**Comment by onein528** [comment]
I'm gonna.
What do you mean?

**Comment by DeveloperWOW64** [comment]
> What do you mean?

What are you asking about?

**Comment by onein528** [comment]
Whay did you say "oops"

**Comment by DeveloperWOW64** [comment]
> @DeveloperWOW64 Why did you say "oops"

I thought I accidentally rebased the PR to gu12 into login-page refactor not vice versa, but nvm
just merge

**Pull request merged**
