### PR TITLE
Implementing profile editing

### PR DESCRIPTION
**Pull request by hunterlan**
### ⏱️ Before you start

- [ x ] Have you checked if a similar PR has already been requested? 
- [ x ] Have you built and ran the app?

### ↗️ Related/Fixed issues

- Related: #215 
- Fixed: #215 

### 📄 Description

Implemented edit profile. Added a vertical scroll bar and email field.

### 💭 Motivation and Context

This PR will solve issue #215 

### 📸 Assets (if appropriate):

image

### CODE REVIEW

**Comment by onein528** [comment]
We don't implement those features until the app gets v0.5. Besides, we use Octokit.GraphQL.NET instead of Octokit.NET

I'm sorry

**Comment by onein528** [comment]
But you can still remain this.

**Comment by hunterlan** [comment]
> We don't implement those features until the app gets v0.5.

But why? And what should be implemented for now, and what shouldn't?

**Comment by onein528** [comment]
Actually we have loadmap.

-v0.5 Completely implemented all of querying feature without harmful bugs.
-v0.9 Completely implemented all of mutation features without harmful bugs.
-v1.0 Final checking and fix all of issues on GitHub.

**Comment by onein528** [comment]
But I'm not sure it is a good idea. I think these days that we should implement some of mutation feature.

**Pull request closed without merging**
