### PR TITLE
General Updates 16

### PR DESCRIPTION
**Pull request by onein528**
### ⏱️ Before you start

- [x] Have you checked if a similar PR has already been requested? 
- [x] Have you built and ran the app?

### ↗️ Related/Fixed issues

_None_

### 📄 Description

Official General Updates round 16.

### 💭 Motivation and Context

It takes a lot of time to do those two to-dos, and it still takes a while to merge this PR.

#### Issue
- [x] Query all required Issue timeline event data
- [x] Added all Issue timeline event item data templates
- [ ] Completely updated/improved Issue page

#### PR
- [ ] Query all required PR timeline event data
- [ ] Added all PR timeline event item data templates
- [ ] Completely updated/improved PR page

### 📸 Assets (if appropriate):

image

### CODE REVIEW

**Comment by onein528** [comment]
@DeveloperWOW64 this will be GU16 or 17.

**Comment by DeveloperWOW64** [comment]
@onein528 This is a common error: 
image
Blank spaces appear in space of non-existent events.

**Comment by DeveloperWOW64** [comment]
And I also noticed this recently:
image
User details don't show in settings page.

**Comment by onein528** [comment]
Yes. A lot of things that I must fix/implement...

**Comment by DeveloperWOW64** [comment]
> Yes. A lot of things that I must fix/implement...

Haha don't worry! I'm here for you too.

**Comment by onein528** [comment]
Thank you. If you have any idea/thought/, let me know.

**Comment by DeveloperWOW64** [comment]
@onein528 What is the use of the Constants file in FluentHub.Core?

**Comment by mousemaid** [comment]
Hi!

**Comment by DeveloperWOW64** [comment]
@onein528 You might want to set the public org email to 'fluenthub-uwp@outlook.com' since it makes more sense than yours.

**Comment by DeveloperWOW64** [comment]
@onein528 I think instead of having repo favourites be just a list of stars, we should have the favourites section be a list of starred sections. As in, stars have the ability to be grouped, so we should display the group names and number of stars *in the group* in the Favourites section. Should the user only use un-grouped stars, we could just hide the Favourites expander section altogether.

However, perhaps this isn't queryable since starred groups are a new feature.

**Comment by onein528** [comment]
> @onein528 I think instead of having repo favourites be just a list of stars, we should have the favourites section be a list of starred sections. As in, stars have the ability to be grouped, so we should display the group names and number of stars _in the group_ in the Favourites section. Should the user only use un-grouped stars, we could just hide the Favourites expander section altogether.
> 
> However, perhaps this isn't queryable since starred groups are a new feature.

Yes. Not queryable. And favorite section is user owned repository list, starred repos are generally not user owned.

**Comment by onein528** [comment]
azp /run

**Review by ioapiset — APPROVED** [review]
LGTM. Shipit v0.3.6

**Pull request merged**
