### PR TITLE
General Updates 9

### LINKED ISSUE #146: Users have unformatted icons
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

0.3.0.0 | X64 | DEBUG

### Description

(for me, at least) 
My user icon in the top right is not formatted to display correctly in the circle.

### Steps To Reproduce

_No response_

### Expected behavior

Should be formatted to fit in the circle as a full icon

### Relevant Assets

image

### PR DESCRIPTION
**Pull request by onein528**
### Before you start...

- [x] Have you updated the FluentHub? You might be using an old version.
- [x] Have you checked if similar issue have already been reported?

### Resolved / Related Issues

- Fixes #146

### Validation

- [x] Built and ran the app
- [x] Tested the changes for accessibility

#### Renewed notifications page and added notification indicator
image

#### Renewed home page
image

#### To see user activities, click this button
image

#### Improved activities page
image

### CODE REVIEW

**Comment by DeveloperWOW64** [comment]
Looking Good!!

**Comment by DeveloperWOW64** [comment]
Bug: Upon opening a folder from within a repo, you get NullReferenceException
image

**Comment by onein528** [comment]
this is always?

**Comment by DeveloperWOW64** [comment]
> this is always?

only on debug it seems

**Comment by onein528** [comment]
No, when you open any folder, occur this exception?

**Comment by DeveloperWOW64** [comment]
> No, when you open any folder, occur this exception?

I've only tried it once - let me see if it does for all repos

**Comment by DeveloperWOW64** [comment]
Sorry: It was a one time only thing

**Comment by DeveloperWOW64** [comment]
Ok. FluentHub will randomly throw NullReferenceException and then wont do it again: its very weird

**Comment by onein528** [comment]
Need to track. sorry that I have deved terrible app...

**Comment by DeveloperWOW64** [comment]
> Need to track. sorry that I have deved terrible app...

WHAT FLUENTHUB IS THE BEST APP EVER

**Comment by onein528** [comment]
woow. I didn't expect that you say so hahaha
thank you so much and I will do better than.

**Comment by DeveloperWOW64** [comment]
Well yes - it could do with some improvements - but there's no need to say that - as I said, it's better than I could have ever done.
PS: Can I add myself here?
image

**Comment by onein528** [comment]
you can, of course!

**Comment by DeveloperWOW64** [comment]
> you can, of course!

good! I'll add it to gu9

**Comment by onein528** [comment]
whichever. choose which you want to

**Comment by DeveloperWOW64** [comment]
> whichever. choose which you want to

main

**Comment by DeveloperWOW64** [comment]
#151

**Comment by DeveloperWOW64** [comment]
image

**Comment by DeveloperWOW64** [comment]
When do you plan to commit this PR?

**Comment by onein528** [comment]
when I finished developing and improving of activities page fully.

image

**Comment by DeveloperWOW64** [comment]
Ok. I'll see what else I can do on this PR

**Comment by onein528** [comment]
should not change `App Settings` to `Settings` bacause user may confuse if it is signed in user "GitHub" settings or just FluentHub settings

**Comment by DeveloperWOW64** [comment]
> should not change `App Settings` to `Settings` bacause user may confuse if it is signed in user "GitHub" settings or just FluentHub settings

Don't you plan for fluenthub://settings to be like github.com/settings/ ?

**Comment by onein528** [comment]
what do you mean?

`fluenthub://settings` is App Settings and not GitHub user profile settings.
`github.com/settings` is GitHub user profile settings.

**Comment by DeveloperWOW64** [comment]
> what do you mean?
> 
> `fluenthub://settings` is App Settings and not GitHub user profile settings. `github.com/settings` is GitHub user profile settings.

As in, do you plan for fluenthub://settings to have similar content to github.com/settings

**Comment by onein528** [comment]
Never. it is just app settings and should divide contents (for "continue with your browser")

**Comment by DeveloperWOW64** [comment]
> Never. it is just app settings and should divide contents (for "continue with your browser")

Ok. While I do agree, I still think it should be 'settings', as the chance of confusion is low and 'App Settings' looks slightly off.
However, your app, your choice.

**Comment by onein528** [comment]
OK.

**Comment by DeveloperWOW64** [comment]
> OK.

wdym?

**Comment by onein528** [comment]
Leave your changes(I dont revert)

**Comment by onein528** [comment]
Finally, updated activities page:

image

**Comment by onein528** [comment]
and I have to fix some ptential issues.

@DeveloperWOW64 Also can you check if these changes work properly?

**Comment by DeveloperWOW64** [comment]
> and I have to fix some ptential issues.
> 
> @DeveloperWOW64 Also can you check if these changes work properly?

I dont have lots of time rn: maybe in an hour

**Comment by onein528** [comment]
FYI, some buttons and other controls have no fuction.

Like this:
image

**Comment by onein528** [comment]
5/23/2022 now

```
github.com/AlDanial/cloc v 1.92  T=298.48 s (3.4 files/s, 907.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#                             596           8883           6493         108209
XML                            199           1547           6662          55242
JSON                            10              0              0          40503
XAML                           216           3943            488          33814
CSS                              3            470              0           2341
MSBuild script                   3              0             21           1620
CSV                              1              0              0            547
HTML                             1              0              0             21
-------------------------------------------------------------------------------
SUM:                          1029          14843          13664         242297
-------------------------------------------------------------------------------
```

**Comment by DeveloperWOW64** [comment]
I've got some time now - I was making cookies.

**Review by DeveloperWOW64 — COMMENTED** [review]
Good! There are two things that could be addressed:
a) bots dont show their true avatars
image
b) what are these errors doing here?
image

**Comment by onein528** [comment]
(a) There’s nothing we can do. maybe GitHub API spec.

(b) I can fix these errors(static code analysis).

**Comment by onein528** [comment]
mergeable.

some other feature should be added by a new PR.

Please review. @DeveloperWOW64

**Review by DeveloperWOW64 — DISMISSED** [review]
Good. Debugging, I found a couple of mistakes in grammar but I'll fix soon.
I'll let you know when completely mergeable.

**Review by DeveloperWOW64 — APPROVED** [review]
~~Changed and fixed all grammar mistakes I can see.
Ready to merge.~~
Just noticed a bit more; sorry for the constant dismissal of reviews

**Comment by DeveloperWOW64** [comment]
👏👏

**Pull request merged**
