### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by onein528**

### CODE REVIEW

**Comment by DeveloperWOW64** [comment]
Sooooo... We need to add all the locale resources *again*?

**Comment by DeveloperWOW64** [comment]
WOAH that's a lot of-- Thanks.

**Comment by DeveloperWOW64** [comment]
BTW @onein528 Norway uses 3 languages, no-NO, nb-NO, nn-NO. Windows doesn't seem to support no-NO locale (called Samisk in Norwegian) so we should use nb-NO (Bokmål) or nn-NO (Nynorsk).

**Comment by onein528** [comment]
Can you fix that?

**Comment by DeveloperWOW64** [comment]
Why the close? @onein528

**Review by ioapiset — DISMISSED** [review]
LGTM.

**Comment by DeveloperWOW64** [comment]
OK. I'll make FluentHub localisable.

**Comment by onein528** [comment]
Why added xlfs? It seems not to be needed.

**Comment by DeveloperWOW64** [comment]
> Why added xlfs? It seems not to be needed.

Ah. Then you can use Multilingual Application Toolkit Editor.

**Comment by DeveloperWOW64** [comment]
Crowdin is very difficult to use personally, I always prefer the MAT editor.

**Comment by onein528** [comment]
Why..

1. https://crowdin.com/project/fluenthub
2. Click a flag that you wanna edit its resource

    image

3. Click `Resources.resx`

    image

4. Edit here

    image

5. Save them

What you do is just those 5 steps.

Opening PR is my job(of course, If you can, you can do it)

**Comment by onein528** [comment]
Nooooooooooooo!!!!!!!!!!!!! What....

If you wanna add new resources, use a new branch and open a new PR.
This PR is 'automatically' created and add new translated resources.

**Comment by onein528** [comment]
I will merge this PR.

**Comment by onein528** [comment]
azp /run

**Review by DeveloperWOW64 — APPROVED** [review]
LGTM.

**Pull request merged**
